# Generated by Django 4.1.5 on 2023-01-17 20:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('capacityMeasure', models.CharField(choices=[('ml', 'Ml'), ('g', 'G'), ('item', 'Item')], default='item', max_length=255)),
                ('container', models.CharField(choices=[('can', 'Can'), ('tube', 'Tube'), ('jar', 'Jar'), ('pack', 'Pack'), ('block', 'Block'), ('item', 'Item')], default='item', max_length=255)),
                ('on_hand', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('pantryItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPantryApi.pantryitem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPantryApi.recipe')),
            ],
        ),
    ]
