# Generated by Django 4.1.5 on 2023-02-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPantryApi', '0003_pantryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='imageSrc',
            field=models.URLField(null=True),
        ),
    ]
