# Generated by Django 4.1.5 on 2023-02-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPantryApi', '0005_pantryitemcategory_icon_alter_pantryitem_imagesrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imageSrc',
            field=models.URLField(blank=True, null=True),
        ),
    ]
