# Generated by Django 4.1.5 on 2023-04-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPantryApi', '0006_recipe_imagesrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serves',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
