# Generated by Django 4.1.5 on 2023-04-25 18:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myPantryApi', '0007_recipe_serves'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('pantryItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPantryApi.pantryitem')),
            ],
        ),
    ]
